version: '2'
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:6.2
    container_name: redis-node-0
    networks:
      - redis
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:6.2
    container_name: redis-node-1
    networks:
      - redis
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:6.2
    container_name: redis-node-2
    ports:
      - "6379:6379"
    depends_on:
      redis-node-0:
        condition: service_started
      redis-node-1:
        condition: service_started
    networks:
      - redis
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDISCLI_AUTH=redis'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_CLUSTER_CREATOR=yes'

networks:
  redis:
    driver: bridge
